### ISSUE TITLE
Error running inference on video

### ISSUE THREAD

**Issue by jamalknight** [vegesm/pose_refinement#2]
hi there

After following the installation steps, I get an error when running inference on a video.

Running:
`python scripts/predict.py -r 00_03.mp4 output.pkl`

Error:
```
Traceback (most recent call last):
  File "scripts/predict.py", line 6, in <module>
    from databases.datasets import FlippableDataset
ModuleNotFoundError: No module named 'databases.datasets'
```
It seems that there are errors on the libraries to import:
```
from databases.datasets import FlippableDataset
from databases.joint_sets import MuPoTSJoints, CocoExJoints
from model.pose_refinement import optimize_poses
from scripts.eval import load_model, LOG_PATH
from training.callbacks import TemporalTestEvaluator
from training.preprocess import SaveableCompose, MeanNormalize3D, get_postprocessor
from util.misc import load, save, ensuredir
from util.pose import extend_hrnet_raw
from scripts import maskrcnn_bboxes, hrnet_predict
```
I am in the conda environment `'pose-refinement'`

thanks

**Comment by vegesm** [comment]
Run the code from the src directory.

**Comment by jamalknight** [comment]
Hi there

Running the code in the src directory has same error:
```
(pose-refinement) jamal@walrus:/media/jamal/jknight_3TB/projects/pose_refinement/src$ python scripts/predict.py -r 00_03.mp4 output.pkl
Traceback (most recent call last):
  File "scripts/predict.py", line 6, in <module>
    from databases.datasets import FlippableDataset
ModuleNotFoundError: No module named 'databases.datasets'
```

I am wondering if there might be something missing from my conda environment?

`conda list`

```
# packages in environment at /home/jamal/anaconda3/envs/pose-refinement:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.11.0                   pypi_0    pypi
aiocontextvars            0.2.2                      py_0    conda-forge
aiomysql                  0.0.21             pyhd8ed1ab_0    conda-forge
aiosqlite                 0.16.0             pyhd8ed1ab_0    conda-forge
asyncpg                   0.21.0           py36h1d69622_2    conda-forge
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py36h5fab9bb_1    conda-forge
cffi                      1.14.4           py36h261ae71_0  
chardet                   4.0.0                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
contextvars               2.4                        py_0    conda-forge
cryptography              3.3.1            py36h3c74f83_0  
cudatoolkit               10.1.243             h6bb024c_0  
cudatoolkit-dev           10.1.243             h516909a_3    conda-forge
cython                    0.29.21                  pypi_0    pypi
databases                 0.4.1            py36h5fab9bb_1    conda-forge
detectron2                0.3+cu101                pypi_0    pypi
ffmpeg                    4.2.2                h20bf706_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.2.post20210115          pypi_0    pypi
gmp                       6.1.2                h6c8ec71_1  
gnutls                    3.6.5             h71b1129_1002  
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
immutables                0.14             py36h8c4c3a4_1    conda-forge
importlib-metadata        3.4.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
iopath                    0.1.2                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
json-tricks               3.15.5                   pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libvpx                    1.7.0                h439df22_0  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.3                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.2.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
nettle                    3.4.1                hbb512f6_0  
ninja                     1.10.2           py36hff7bd54_0  
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py36_0  
opencv3                   3.1.0                    py36_0    menpo
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1i               h27cfd23_0  
pillow                    8.1.0            py36he98fc37_0  
pip                       20.3.3           py36h06a4308_0  
portalocker               2.0.0                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydot                     1.4.1                    pypi_0    pypi
pymysql                   0.9.2              pyhd3deb0d_0    conda-forge
python                    3.6.12               hcff3b4d_2  
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   1.5.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7                      pypi_0    pypi
setuptools                51.1.2           py36h06a4308_4  
six                       1.15.0           py36h06a4308_0  
sqlalchemy                1.3.5            py36h516909a_0    conda-forge
sqlite                    3.33.0               h62c20be_0  
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.4.1                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torchvision               0.6.1                py36_cu101    pytorch
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.2                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
x264                      1!157.20191217       h7b6447c_0  
xz                        5.2.5                h7b6447c_0  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd 
```

**Comment by vegesm** [comment]
databases.datasets is part of the repository. Maybe you haven't downloaded it?

**Comment by aoussou** [comment]
@vegesm 

I have the same issue on Ubuntu 18.04. What OS are you using?
It kind of works if I hack the files by adding

```
import sys
sys.path.append('../../src')
```

But it's not a good solution.

**Comment by vujosp** [comment]
There are few ways on how to address this issue.

1. if you are using the terminal
PYTHONPATH=. python scripts/predict.py -r video.mp4 output.pkl

2. (my preferred way) in your IDE select the source files:
for example in PyCharm 
In File/Settings/Project: (name)/Project Structure/ right mouse click on src and mark it as a source (it will turn blue)
![Screenshot from 2021-06-10 11-12-49](https://user-images.githubusercontent.com/81373080/121498716-fb3d0380-c9dc-11eb-8d08-c5963dcda0cb.png)

Hope it helps,
Cheers!

**Comment by boza-wd** [comment]
There are few ways on how to address this issue.

    if you are using the terminal
    PYTHONPATH=. python scripts/predict.py -r video.mp4 output.pkl

    (my preferred way) in your IDE select the source files:
    for example in PyCharm
    In File/Settings/Project: (name)/Project Structure/ right mouse click on src and mark it as a source (it will turn blue)
![Screenshot from 2021-06-10 11-13-48](https://user-images.githubusercontent.com/81355992/121499162-6a1a5c80-c9dd-11eb-9e2d-aab6b832b0c1.png)

Hope it helps,
Cheers!
