### ISSUE TITLE
Generate Muco-Temp

### ISSUE THREAD

**Issue by amek-aymen** [vegesm/pose_refinement#9]
Hi, first of all thank you for sharing your great work.

I wanted to recreate the frames of the Muco-Temp dataset, generated from mpii-3dhp. When I launch the "generate_muco_temp.py" program, I get some images then it crashes before finishing.

I have this error:

_**img = chair_mask * img + (1 - chair_mask) * pose_img
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "scripts/generate_muco_temp.py", line 77, in <module>
    p.starmap(generate_vid_frames, params)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'**_

Could you please help me with that?
Thanks for your time in advance.

**Comment by JasonChen-Coder** [comment]
Hello, I also had problems running this code. Have you solved this problem?
